sous-chefs/hashicorp-vault

- test/integration/default/serverspec/default_spec.rb
> Update tests for SSL cert/key to match attributes

- libraries/vault_config.rb
This fixes #8. Tested to work with Vault 0.4.0.
> Fix tls_disable with vault 0.4.0

- libraries/vault_installation_binary.rb
- metadata.rb
This was a stupid issue on my end since I never tested with x32
architectures.
> Fix binary installation for i386 architectures.

- attributes/default.rb
- libraries/vault_installation_binary.rb
- metadata.rb
- test/integration/default/serverspec/default_spec.rb
- test/unit/libraries/vault_config_spec.rb
- test/unit/libraries/vault_service_spec.rb
- test/unit/recipes/default_spec.rb
Upgrades hashes to new version of Vault
> Vault 0.6.0

- .kitchen.yml
- Berksfile
Just some kitchen improvements
> Add default recipe to kitchen run_list

- attributes/default.rb
- libraries/vault_installation_binary.rb
- test/integration/default/serverspec/default_spec.rb
- test/unit/libraries/vault_service_spec.rb
- test/unit/recipes/default_spec.rb
Vault 0.6.1 is released: https://github.com/hashicorp/vault/blob/master/CHANGELOG.md#061-august-22-2016
> Add support of Vault 0.6.1

- libraries/vault_config.rb
Simple change to allow cluster_address config option for listener options.
> Add cluster_address for listener options

- attributes/default.rb
- libraries/vault_config.rb
- libraries/vault_installation_binary.rb
- test/integration/default/inspec/default_spec.rb
- test/unit/libraries/vault_service_spec.rb
- test/unit/recipes/default_spec.rb
Changes:
* Bumped default version to 0.6.2
* Add cache_size config option (new in 0.6.2)
> Add 0.6.2 support

- libraries/vault_service.rb
Also could you cut a new version, so we can use this to enable debug logging for troubleshooting.
> Add log-level support for service

- libraries/vault_secret.rb
- small typo fix in error message from vault_secret.
> fix typo in error message

- libraries/vault_secret.rb
- add ssl_pem_contents to attributes (can be used in place of ssl_pem_file)
- add ssl_ca_cert attribute.
> add additional ssl options to vault_secret

- attributes/default.rb
- libraries/vault_installation_binary.rb
- libraries/vault_installation_git.rb
- libraries/vault_secret.rb
- test/integration/default/inspec/default_spec.rb
- test/unit/libraries/vault_service_spec.rb
- test/unit/recipes/default_spec.rb
Added shasums for version 0.6.4 and 0.6.5 and fixed the style issues preventing travis from passing.
> Added shasums for vault 0.6.4 and 0.6.5

- libraries/vault_installation_package.rb
Same issues and fixes as outlined in https://github.com/johnbellone/consul-cookbook/pull/398
> Fix package installation

- libraries/vault_secret.rb
- libraries/vault_service.rb
- metadata.rb
- test/unit/libraries/vault_service_spec.rb
- Update vault::service library to remove deprecation warnings
- Update metadata to correct Foodcritic errors
> library update for Chef 13

- Dangerfile
Remove labels requirement
[List any existing issues this PR resolves]
> remove labels

- CHANGELOG.md
- libraries/vault_config.rb
- metadata.rb
Add plugin_directory config.
Fixes #136
> Add plugin_directory config.

- CHANGELOG.md
- kitchen.yml
- libraries/vault_config.rb
Last release before I push the resource rewrite to master.
> v3.0.1 release

- CHANGELOG.md
Signed-off-by: PowerSchill <Mark.Schill@cmschill.net>
[Describe what this change achieves]
[List any existing issues this PR resolves]
> Updates Changelog

- attributes/default.rb
- libraries/helpers.rb
- libraries/vault_config.rb
- libraries/vault_installation.rb
- libraries/vault_installation_binary.rb
- libraries/vault_installation_git.rb
- libraries/vault_installation_package.rb
- libraries/vault_secret.rb
- libraries/vault_service.rb
- recipes/default.rb
- recipes/gems.rb
auto-corrected with cookstyle
Signed-off-by: Tim Smith <tsmith@chef.io>
> Use chef style comment headers

- .rubocop.yml
- CHANGELOG.md
- Dangerfile
- metadata.rb
- test/cookbooks/test/metadata.rb
> Miscellaneous Fixes

- .circleci/config.yml
- README.md
- kitchen.dokken.yml
> Adds RHEL 8 family support

- README.md
> Closes #178

- .github/workflows/ci.yml
- CHANGELOG.md
- kitchen.yml
- libraries/vaultAgentTemplateCollection.rb
- resources/agent_config.rb
- resources/agent_install.rb
- resources/agent_template.rb
- resources/install.rb
- resources/install_dist.rb
- resources/service.rb
- test/cookbooks/test/recipes/agent_install.rb
- test/integration/agent_install/inspec/default_spec.rb
This PR has everything needed to configure and install vault agents
- #144
> Vault agent support

- .github/workflows/ci.yml
- CHANGELOG.md
- kitchen.dokken.yml
- kitchen.yml
- libraries/install.rb
- resources/install.rb
support amazonlinux on ark installation
> support amazon on ark installation

- CHANGELOG.md
- libraries/template.rb
- resources/service.rb
- templates/default/vault/hcl.erb
- test/cookbooks/test/recipes/agent_hcl.rb
- test/cookbooks/test/recipes/agent_json.rb
- test/cookbooks/test/recipes/server_hcl.rb
- test/cookbooks/test/recipes/server_hcl_ark.rb
- test/cookbooks/test/recipes/server_json.rb
Refactor service action to use standard action and allow multiple actions
- n/a
> Refactor service action to use standard action and allow multiple actions

- .github/workflows/ci.yml
- .overcommit.yml
- CHANGELOG.md
- kitchen.dokken.yml
- kitchen.yml
This PR will standardise the files we have with out agreed spec in sous-chefs/repo-management.
This repo has been identified by topic(s) of chef-cookbook
> Automated PR: Standardising Files
