sous-chefs/hashicorp-vault

attributes/default.rb

There were two default attributes that might have been missed on the last rework of the vault_config HWRP. 
``` attribute(:address, kind_of: String)  # formerly :listen_address```
```attribute(:tls_disable, kind_of: String, default: "")```
Based on this information I removed the tls_disable default as it was a bool and we are expecting a string, in addition we default that string in the provider.   
listen_address was also updated based on the comments.
As always, great work on this cookbook @johnbellone.

fixing default attributes based on HWRP

---

Berksfile

Using the HEAD of a cookbook project is a bit dangerous, since it’s a moving target.
We need some features/fixes that are only available in unreleased code for chef-vault.
Choosing a known-good ref is the next best thing to using a released version.

Pin chef-vault to specific ref

---

test/integration/default/serverspec/default_spec.rb

* The `should` syntax is deprecated
* The `contains` syntax is also deprecated

Update Serverspec assertions as per Rspec 3

---

.kitchen.yml
attributes/default.rb
libraries/vault_config.rb
test/integration/no_cert_mgmt/serverspec/default_spec.rb
test/integration/tls_disable/serverspec/default_spec.rb

The prescription by this cookbook to manage the TLS certificate, using chef-vault, is overly strong, and, while it is an excellent practice, may not jibe with some potential users’ workflows.
Builds on #4 to use the `VaultConfig#tls?` method to control whether or not the certificate files are managed. All credit to @zarry!

Make the TLS certificate management optional

---

attributes/default.rb

Simply adding the check sums for the most recent version and upping the default version to the most recently  released, `v0.3.1`.
QA
----
Check sum values for vault `v0.3.1` can be downloaded and verified from this link:
https://releases.hashicorp.com/vault/0.3.1/vault_0.3.1_SHA256SUMS
Found on https://vaultproject.io/downloads.html

Modify attributes to support vault 0.3.1

---

attributes/default.rb

This PR adds checksums for artifacts of Vault v0.5.0 and changes the default version to 0.5.0

Add support for Vault 0.5.0

---

libraries/vault_config.rb

- Enable Boolean and Fixnum values (which are legal as values in a Ruby hash and a Vagrantfile's `chef.json`) to the String values expected by the cookbook's attribute parser.
- Fix issue #40.

Coerce tls_disable attribute to a string.

---

attributes/default.rb
libraries/vault_config.rb
libraries/vault_installation_binary.rb
libraries/vault_service.rb
recipes/default.rb

* Re-named prefix from vault to hashicorp-vault to fix inversion error
* Added attributes to vault_config
* Re-worked to_json method to place configs in appropriate sections
* Fixed incorrect method call in vault_installation_binary provider
* Added vault 0.5.1 checksums
* Added 'server' arguement to service.command

Fixed Install Issues

---

libraries/vault_config.rb

Re-submitting fix contained in #45 
This PR for johnbellone/rubyzip-cookbook#1 should be merged as well. Otherwise Chef clients `< 12.5` won't be able to use this cookbook.

Fixed typo in vault_config provider property

---

.travis.yml
attributes/default.rb
libraries/vault_secret.rb
recipes/gems.rb

This resource fetches a secret from Vault & stores it in the node's run_state for the duration the Chef run. It also supports renewing secrets by caching the path on the node object & renewing it on the next Chef run.
```ruby
ENV['VAULT_TOKEN'] = 'GUID'
vault_secret 'secret/recipes/burgers' do
address 'https://vault.example.com'
token 'GUID'
ssl_verify false
attempts 5
notifies :create, "file[/tmp/test]", :immediately
end
file '/tmp/test' do
action :nothing
content lazy { node.run_state['secret/recipes/burgers'].data[:ingredients] }
owner 'root'
group 'root'
mode '0640'
end
```

Added a resource for reading secrets from Vault

---

libraries/vault_service.rb

Vault server restart is even more harmful than consul restart (related: https://github.com/johnbellone/consul-cookbook/issues/288).
Vault server restart means that Vault becomes sealed and stops process incoming requests. So, regardless of the reason, it should be done only by an operator.

Prevent "vault" service to be restarted on update

---

libraries/vault_service.rb
templates/default/systemd.service.erb
templates/default/sysvinit.service.erb

* Add custom template for "sysvinit" service provider. Purposes are the same as in https://github.com/johnbellone/consul-cookbook/pull/266
* Add custom template for "systemd" service provider. Purposes are the same as in https://github.com/johnbellone/consul-cookbook/commit/66bf9389c81011abca23b65898e82e9e783c1508
* Don't force "sysvinit" to be a service provider for all platforms. 
There is no any reference to the reason why the provider has been hard-coded here. Probably, it was just a typo in https://github.com/johnbellone/vault-cookbook/commit/093f198e5ed73baeb308d4a5cae7e30f40794f65#diff-224e63197dffc5bf0dae729286b58f64R92. Please, correct if it is not so.

Use custom templates for "systemd" and "sysvinit" service providers

---

libraries/vault_secret.rb

It allows avoiding conflicts with other top-level attributes.
Related comment: https://github.com/johnbellone/vault-cookbook/commit/7f2f49d7054887bd0d7fff87acc6067944a19948#commitcomment-17324222
cc: @Ginja

vault_secret: Save lease ID to the nested attribute

---

libraries/vault_secret.rb

It fixes an error:
```
================================================================================
Error executing action `read` on resource 'vault_secret[secret/secretpath]'
================================================================================
TypeError
---------
no implicit conversion of String into Integer
Cookbook Trace:
---------------
/tmp/kitchen/cache/cookbooks/hashicorp-vault/libraries/vault_secret.rb:66:in `[]'
/tmp/kitchen/cache/cookbooks/hashicorp-vault/libraries/vault_secret.rb:66:in `block (2 levels) in <class:VaultSecret>'
/tmp/kitchen/cache/cookbooks/poise/files/halite_gem/poise/helpers/subcontext_block.rb:54:in `instance_eval'
/tmp/kitchen/cache/cookbooks/poise/files/halite_gem/poise/helpers/subcontext_block.rb:54:in `subcontext_block' …
```

Fix default value of "leases" attribute

---

.kitchen.yml
attributes/default.rb
libraries/vault_installation_binary.rb
libraries/vault_installation_git.rb
libraries/vault_service.rb
metadata.rb
test/integration/default/serverspec/default_spec.rb
test/unit/libraries/vault_service_spec.rb
test/unit/recipes/default_spec.rb

This change:
* adds support for Vault 0.5.3
* fix for missing `libcap2-bin` package, required for Debian 7.x kitchen test
* added extra steps needed to compile Vault from source, including a dependency on Go 1.6, path fixes, and a `godep restore` stage
* update the dependency on `build-essential ~> 3.2`

Vault 0.5.3 update (with test fixes, build-essential update)

---

metadata.rb

As far as I can see, there is no any reason to pin `build-essential` version in this cookbook. However, it may cause some conflicts with other cookbooks, like I've noticed here: https://github.com/johnbellone/vault-cookbook/pull/62#issuecomment-227196449
`build-essential` is one of fundamental library cookbook used by a lot of other cookbooks as a dependency. So, if it's really needed, then it's better for users to pin `build-essential` version on the top level, like wrapper cookbook, env cookbook, or Chef Environment, according to release notes
https://github.com/chef-cookbooks/build-essential/blob/master/CHANGELOG.md

Liberate "build-essential" version constraint

---

templates/default/systemd.service.erb

As /var/run is mounted as tmpfs in ubuntu 16.04 it doesn't persist across system restarts.
I have made user permissions only apply to the start job, and the pre start job can then create the work dir in /var/run (/run) which is owned by root. Therefore the prestart job runs as root and creates the dir if it doesent already exist.

Create work dir before service starts as it does not persist across restarts

---

libraries/vault_secret.rb

I think, like in Chef Data Bags, there should be a run failure if the specified secret could not be read by some reason. Otherwise, it makes people to write additional wrappers for checking the secret value.

vault_secret: Raise an exception if Vault read has failed

---

libraries/vault_installation_git.rb

If I try to install vault by using git I get this error.
```bash
* execute[godep restore] action run
================================================================================
Error executing action `run` on resource 'execute[godep restore]'
================================================================================
Mixlib::ShellOut::ShellCommandFailed
------------------------------------
Expected process to exit with [0], but received '1'
---- Begin output of godep restore ----
STDOUT: 
STDERR: godep: open Godeps/Godeps.json: no such file or directory
---- End output of godep restore ----
Ran godep restore returned 1
Cookbook Trace:
---------------
/tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:41:in `run_action' …
```

Remove 'godep restore' for vault versions > 0.5.0

---

templates/default/sysvinit.service.erb

There is bash v3.2.* in RHEL/CentOS 5, which doesn't support this notation for stderr and stdout redirection: `&>> `
The following error occurs:
```
Starting vault: bash: -c: line 0: syntax error near unexpected token `>'
bash: -c: line 0: `ulimit -S -c 0 >/dev/null 2>&1 ;  { /opt/vault/0.6.1/vault server -config=/etc/vault/vault.json &>> /var/log/vault.log & } ; echo $! >| /var/run/vault.pid '
[FAILED]
```
So, we have to use the traditional notation with `2>&1` to keep the compatibility with RHEL/CentOS  5

Fix init script syntax for compatibility with RHEL/CentOS  5

---

test/fixtures/policies/default.rb

It fixes #78 
In #75 we've forced RHEL/CenOS platforms to be provisioned with `sudo::default` in order to add test users, such as "vagrant" and "kitchen", to `/etc/sudoers`. But that's not enough - we should also enable passwordless sudo for them.
Before:
```
#...
kitchen ALL=(ALL)
vagrant ALL=(ALL)
```
After:
```
#...
kitchen ALL=(ALL) NOPASSWD:ALL
vagrant ALL=(ALL) NOPASSWD:ALL
```

Enable passwordless sudo for tests

---

libraries/vault_config.rb

Addition of vault global config option `disable_cache`.
It's been available since 0.4.0, default setting in vault is `false`.
Fixes #84

Add disable_cache config option

---

libraries/vault_service.rb

This PR fixes a compatibility issue with Chef 12.6.0 and below.
A Chef run exits with the following error message:
```No resource or method named `platform_family?' for `VaultCookbook::Provider::VaultService ""'```

Fix error due to missing method 'platform_family?'

---

.kitchen.dokken.yml
.kitchen.yml
.travis.yml
README.md

CentOS 5 is deprecated now. Its repodata.xml was moved and this Readme instruction is published on all mirrors:
```
This directory (and version of CentOS) is depreciated.  
CentOS-5 is now past EOL
You can get the last released version of centos 5.11 here:
http://vault.centos.org/5.11/
Please NOTE:  this is not being maintained for security since moving to Vault.
It will have security issues, you should upgrade to a new version instead.
```
http://ftp.uninett.no/centos/5/readme

Remove CentOS 5.11 from TestKitchen configuration

---

attributes/default.rb
libraries/vault_config.rb
libraries/vault_installation_binary.rb
test/integration/default/inspec/default_spec.rb
test/unit/libraries/vault_service_spec.rb
test/unit/recipes/default_spec.rb

This change adds all missing Vault versions SHA sums, from 0.7.0 to 0.8.3.
`vault_config` resource is updated to support new configuration options and remove deprecated ones.
This change would break compatibility with Vault < 0.7.0, so I would suggest to bump cookbook major version.
Fixes #100

Add missing Vault versions and update configuration options

---

libraries/vault_config.rb
metadata.rb

the HA cluster won't start without this global attribute being set. Please review change as I'd rather improve your cookbook than spin off my own fork.

v2.5.1 adding api_addr global attribute to support HA clustering

---

README.md

merely updates the badge in the readme to point to the new circleci build

README: update badges per meta/99

---

README.md

- cookbook name is hashicorp-vault rather than vault
Correct the badge in the README.

Use the correct cookbook name for the Supermarket badge

---

libraries/helpers.rb

The functions `config_prefix_path` and `data_path` are exists on both ![Vault](https://github.com/sous-chefs/vault/blob/master/libraries/helpers.rb#L37-L43) and ![Consul](https://github.com/sous-chefs/consul/blob/master/libraries/helpers.rb#L39-L45) cookbooks and they conflicting with each other.
Both gets the config and data path like vault functions get `config_prefix_path=/etc/vault` whereas consul get `config_prefix_path=/etc/consul`. Whichever runs last is getting precedence. 
In my case, vault runs later. So the `config_prefix_path` of consul is changed to `/etc/vault` instead of `/etc/consul`
```
Recipe: consul::default
* poise_service_user[consul] action create[2019-06-10T17:49:10+01:00] INFO: Processing poise_service_user[consul] action create (consul::default line 7) …
```

Changing the name of conflicting unused helper function names

---

CHANGELOG.md
resources/config.rb
resources/install.rb
resources/service.rb
templates/systemd.service.erb
templates/sysvinit.service.erb
test/integration/server_install/inspec/default_spec.rb

Allow running LimitNOFILE in Vault avoiding the issue with file descriptors being exhausted
Will resolve https://github.com/sous-chefs/vault/issues/190

Added bility to tune LimitNOFILE to fix #190

---

CHANGELOG.md
resources/config.rb
resources/install.rb

This PR adds option for unauthenticated metrics access to `/v1/sys/metrics`
https://www.vaultproject.io/docs/configuration/listener/tcp#unauthenticated_metrics_access

Include config option 'unauthenticated_metrics_access'

---

CHANGELOG.md
libraries/install.rb

Support ark installation for `aarch64`/`i386`/`x86_64` architectures.
https://releases.hashicorp.com/vault/1.6.2/

support aarch64/i386/x86_64 architectures
